// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl4ajM3FOknOswObFoBDMIM2LpNvAN-tw',
    appId: '1:500904762182:web:23f71c2e6eaf50d358e347',
    messagingSenderId: '500904762182',
    projectId: 'shantika-agen',
    authDomain: 'shantika-agen.firebaseapp.com',
    storageBucket: 'shantika-agen.firebasestorage.app',
    measurementId: 'G-X5NEN1DE5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi08Wz3X_aJ2c4Amc-ZOxhZ3CPjJyh4Qs',
    appId: '1:500904762182:android:6a3123939a5b29ac58e347',
    messagingSenderId: '500904762182',
    projectId: 'shantika-agen',
    storageBucket: 'shantika-agen.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH8mTy8aP7fU4QnOlNu3oypwaASj9Ut0s',
    appId: '1:500904762182:ios:908e5c08d66ca50d58e347',
    messagingSenderId: '500904762182',
    projectId: 'shantika-agen',
    storageBucket: 'shantika-agen.firebasestorage.app',
    iosBundleId: 'com.example.shantikaAgen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH8mTy8aP7fU4QnOlNu3oypwaASj9Ut0s',
    appId: '1:500904762182:ios:908e5c08d66ca50d58e347',
    messagingSenderId: '500904762182',
    projectId: 'shantika-agen',
    storageBucket: 'shantika-agen.firebasestorage.app',
    iosBundleId: 'com.example.shantikaAgen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDl4ajM3FOknOswObFoBDMIM2LpNvAN-tw',
    appId: '1:500904762182:web:49d0ac2ba1af018658e347',
    messagingSenderId: '500904762182',
    projectId: 'shantika-agen',
    authDomain: 'shantika-agen.firebaseapp.com',
    storageBucket: 'shantika-agen.firebasestorage.app',
    measurementId: 'G-3TJ2Q7GGJM',
  );

}